### ISSUE TITLE
ChromeDriver only supports characters in the BMP. So many emojis may be invalid.

### ISSUE THREAD

**Issue by aahnik** [aahnik/wappdriver#35]
This is a known issue and any help would be appreciated.

```
2020-11-04 20:17:32,656 - 
Message not sent

Message: unknown error: ChromeDriver only supports characters in the BMP
  (Session info: chrome=86.0.4240.183)
Traceback (most recent call last):
  File "/home/aahnik/.local/lib/python3.8/site-packages/wappdriver/error.py", line 105, in wrapper_func
    vulnerable_func(*args, **kwargs)
  File "/home/aahnik/.local/lib/python3.8/site-packages/wappdriver/driver.py", line 77, in send_text
    msg_box.send_keys(line)  # write a line
  File "/home/aahnik/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/home/aahnik/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/aahnik/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/aahnik/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: ChromeDriver only supports characters in the BMP
  (Session info: chrome=86.0.4240.183)


########################################
```

**Comment by SmartManoj** [comment]
https://stackoverflow.com/a/60478726/5033247

**Comment by jackssn** [comment]
or https://stackoverflow.com/a/61043442/5379091

**Comment by aahnik** [comment]
thanks a lot, @SmartManoj  and @jackssn. I will try the methods you suggested.

**Comment by SmartManoj** [comment]
> or [stackoverflow.com/a/61043442/5379091](https://stackoverflow.com/a/61043442/5379091)

@jackssn all emojis worked?

**Comment by aahnik** [comment]
this is not to be fixed, as i am no more dependant on WhatsApp.

i will completely leave whatsapp on August 2021.

# Switch to telegram
